import type { CategoryMock } from "./types";

export const mockCategories: CategoryMock[] = [
  {
    id: "cat-turkish-blends",
    slug: "turkish-blends",
    name_ar: "خلطات تركي",
    name_en: "Turkish Blends",
    description_ar: "خلطات دافئة مصممة للقهوة التركي اليومية.",
    description_en: "Warm blends designed for everyday Turkish coffee.",
    image: {
      asset_id: "media-category-turkish",
      alt_ar: "عبوة قهوة تركي من لاين كوفي",
      alt_en: "Line Coffee Turkish blend package",
      folder: "Categories",
    },
    sort_order: 1,
    status: "published",
    visible: true,
  },
  {
    id: "cat-espresso-blends",
    slug: "espresso-blends",
    name_ar: "خلطات الإسبريسو",
    name_en: "Espresso Blends",
    description_ar: "خلطات مركزة للكريمة والقوام والرائحة.",
    description_en: "Focused blends for crema, body, and aroma.",
    image: {
      asset_id: "media-category-espresso",
      alt_ar: "حبوب إسبريسو محمصة",
      alt_en: "Roasted espresso beans",
      folder: "Categories",
    },
    sort_order: 2,
    status: "published",
    visible: true,
  },
  {
    id: "cat-easy-coffee",
    slug: "easy-coffee",
    name_ar: "قهوة سهلة",
    name_en: "Easy Coffee",
    description_ar: "اختيارات سريعة بطابع لاين كوفي.",
    description_en: "Easy everyday choices with Line Coffee character.",
    image: {
      asset_id: "media-category-easy",
      alt_ar: "قهوة سهلة التحضير",
      alt_en: "Easy coffee preparation",
      folder: "Categories",
    },
    sort_order: 3,
    status: "published",
    visible: true,
  },
  {
    id: "cat-flavor-coffee",
    slug: "flavor-coffee",
    name_ar: "قهوة بالنكهات",
    name_en: "Flavor Coffee",
    description_ar: "نكهات دافئة ومتوازنة لعشاق القهوة المميزة.",
    description_en: "Warm, balanced flavors for distinctive coffee moments.",
    image: {
      asset_id: "media-category-flavor",
      alt_ar: "قهوة بالنكهات من لاين كوفي",
      alt_en: "Line Coffee flavor coffee",
      folder: "Categories",
    },
    sort_order: 4,
    status: "published",
    visible: true,
  },
  {
    id: "cat-make-your-espresso",
    slug: "make-your-espresso",
    name_ar: "اصنع إسبريسو",
    name_en: "Make Your Espresso",
    description_ar: "تجربة مخصصة لبناء خلطة إسبريسو حسب الذوق.",
    description_en: "A custom experience for building espresso by taste.",
    image: {
      asset_id: "media-category-builder",
      alt_ar: "أدوات بناء خلطة إسبريسو",
      alt_en: "Espresso blend builder tools",
      folder: "Categories",
    },
    sort_order: 8,
    status: "published",
    visible: true,
  },
];
